#minor Lien site – dispositif : avoir sur la fiche d'un site les dispositifs mobilisés
MTES-MCT/action-bidonvilles pull request #125
Opened 2021-05-04 13:40 UTC by gaeldestrem

https://trello.com/c/IljnECdA/931-lien-site-dispositif-avoir-sur-la-fiche-dun-site-les-dispositifs-mobilis%C3%A9s

2021-05-04 14:15 UTC, anis approved these changes

2021-05-04 14:32 UTC, anis requested changes
Voir le feedback fait côté API : le champ "Mené par" doit afficher l'opérateur du dispositif, pas son créateur.
J'ai fait les changements appropriés dans la PR feedback : https://github.com/MTES-MCT/action-bidonvilles/pull/127/files

2021-05-05 07:54 UTC, anis approved these changes

2021-05-10 16:55 UTC, gaeldestrem commented
![image](https://user-images.githubusercontent.com/5053593/117696136-45a24900-b1c1-11eb-94f3-2985b7295895.png)

2021-05-11 08:23 UTC, merged