(641) Formulaire 'Partager vos contacts'
MTES-MCT/action-bidonvilles pull request #44
Opened 2021-01-18 18:25 UTC by ch-benard

**#641: Formulaire "Partager vos contacts"**

**modifiés**:
  - .env.development
  - package.json
  - src/js/app/messages/fr/index.js
  - src/js/app/pages/Contact/index.vue
  - src/js/app/router.js
  - src/js/index.js
  - yarn.lock
  
  **ajoutés**:
  - src/js/app/messages/fr/InvitationPage.json
  - src/js/app/pages/Invitation/
  - src/js/app/store/
  - src/js/helpers/api/invite.js

2021-01-21 11:00 UTC, anis requested changes
Beaucoup de choses, mais quasiment que du code cleaning : voir les commentaires.

Sur la partie UI/UX il y a plusieurs choses qui me dérangent même si tu n'y es pour rien, mais je préfère mettre mes remarques ici quand même :
- le bouton "Ajouter un nouveau contact" marche mal je trouve : je le trouve beaucoup trop loin des inputs
- le div qui résume toutes les erreurs des champs me paraît en trop : il éloigne encore plus le bouton "Ajouter un nouveau contact" des inputs, il prend beaucoup de place, et ne fait que répéter les erreurs qui s'affichent de toute façon déjà sous les inputs
- la différence de style entre le bouton "Ajouter un nouveau contact" et "Inviter" est vraiment étrange
- que la InvitationList utilise des inputs en mode readonly marche mal sur mobile : le fait que ce soit des inputs fait que tu es obligé de les passer en layout colonne et du coup ils prennent *beaucoup* de place. Je pense que ça marcherait mieux si ces infos étaient juste du texte tout inline

2021-01-21 18:58 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                text: "A bientôt."
Non, car pas d'utilisateurs de nationalité autre que française prévus puisqu'il faut être acteur national.

2021-01-21 18:58 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                    title: "Succès",
Non, car pas d'utilisateurs de nationalité autre que française prévus puisqu'il faut être acteur national.

2021-01-21 18:59 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationList.vue
> +<style></style>
Corrigé.

2021-01-21 19:00 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationList.vue
> +    props: ["guestList"],
Corrigé.

2021-01-21 19:01 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationList.vue
> +        delItem(index) {
Noté. C'est corrigé.

2021-01-21 19:04 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +            error: null,
Corrigé.

2021-01-21 19:05 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                this.commonFields.firstname = this.commonFields.lastname = this.commonFields.email =
Noté et corrigé.

2021-01-21 19:06 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                this.$emit("addGuestReq", this.commonFields);
Merci. Corrigé.

2021-01-21 19:07 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                        name="Prénom"
Pas nécessaire. Seul les acteurs nationaux ont accès aux invitations.

2021-01-21 19:07 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                        name="Nom de famille"
Pas nécessaire. Seul les acteurs nationaux ont accès aux invitations.

2021-01-21 19:07 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                        validationName="Email"
Pas nécessaire. Seul les acteurs nationaux ont accès aux invitations.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Contact/index.vue
> +                    let greeter = {
Oui ! Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +<style></style>
Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/store/index.js
> +/* eslint-disable prettier/prettier */
Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/store/index.js
> +    }
Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/store/index.js
> +    }
Effectivement. Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                <div class="max-w-screen-lg mx-auto pb-8">
Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +            error: null
`error` supprimé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +        },
Effectivement, on ne gère pas les langues autres que le français, donc pas nécessaire. Corrigé.

2021-01-21 19:08 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +        }
Corrigé: test sur l'objet greeter. 
- Si null ou undefined, retour à la page d'accueil et affichage d'une notification d'erreur. 
- Si l'objet existe mais vide retour à la page d'accueil et affichage d'une notification d'erreur.

2021-01-21 19:09 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +            }
Erreur de débutant. Je note la bonne pratique. Corrigé.

Il n'y a pas de traduction à faire car la possibilité d'inviter des contacts n'existent que pour les utilisateurs nationaux (vu avec Laure).

2021-01-21 19:09 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +            // Préparation du message de confirmation d'envoi des mails
Je n'ai pas jugé nécessaire de le faire car le bouton "Inviter" n'apparaît que sous condition: `v-if="this.guestList.length > 0"`
J'ai corrigé tout de même. Je teste la taille de la liste. Si > 0 on continue, sinon, retour à la landing page avec affichage d'une notification d'erreur.

2021-01-21 19:09 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                this.loading = true;
Merci. Corrigé.

2021-01-21 19:09 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                this.error = err;
Corrigé. En cas d'erreur, retour vers la landing page et affichage d'une notification d'erreur

2021-01-21 19:09 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                this.$refs.form.setErrors(err.fields);
Je note toutes ces informations. Mais dans la mesure ou on cherche juste à savoir si les invitations ont été envoyées ou non, j'ai simplifié et affiché une notification d'erreur au cas où la méthode `invite` côté API échoue.

2021-02-26 09:33 UTC, ch-benard commented on src/js/app/pages/Invitation/index.vue
> +                }}</Button>
Corrigé.

2021-02-26 09:56 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationList.vue
> +            this.guestList.splice(index, 1);
Très juste, idem, erreur de débutant. Résolu en utilisant un custom event (delete-guest).

2021-02-26 09:58 UTC, ch-benard commented on src/js/app/pages/Invitation/InvitationForm.vue
> +                email: this.$route.query.email || "",
Jamais. Corrigé.

2021-03-30 13:17 UTC, merged