Issue/709
MTES-MCT/action-bidonvilles pull request #52
Opened 2021-02-08 19:16 UTC by ch-benard

2021-02-12 11:04 UTC, anis requested changes
Essentiellement des changements structurels pour s'aligner sur le nouveau design system :
- refondre le composant charte_engagement pour tout mettre dans un seul fichier .vue
- éviter les styles personnalisés pour plutôt utiliser les classes tailwind et sa palette graphique
- utiliser les composants UI déjà existants (Spinner, Checkbox, ...)

2021-02-12 11:04 UTC, anis commented on src/js/app/pages/charte_engagement/charte_engagement.pug
> +                                <img v-else src="/img/spinner_light.svg" width="20" />
Pareil, il existe désormais un composant spécifique pour le spinner : `app/components/ui/Spinner.Vue`
Il est enregistré dans l'espace global, tu peux donc l'utiliser directement (sans avoir à l'importer préalablement) : `<Spinner></Spinner>`

2021-02-12 11:04 UTC, anis commented on src/js/app/pages/charte_engagement/charte_engagement.pug
> +                    <div>Je m'engage également à <strong>exploiter les informations présentes sur la plateforme exclusivement pour les besoins propres de mon organisation ; à ne pas communiquer</stro
Idem qu'au-dessus, utiliser plutôt le nouveau composant `Checbkox.vue` pour mutualiser le style;

2021-02-15 09:23 UTC, gaeldestrem requested changes

2021-02-15 09:23 UTC, gaeldestrem commented on src/js/app/pages/charte_engagement/charte_engagement.js
> +            acceptCharte(
(Retour optionnel)

Je trouve plus lisible d'utiliser des async/await plutôt que des chaines de promise

```
async submit() {
  ...
  await acceptCharte(...)
  setConfig("user.charte_engagement_a_jour", true);
  ...
}
```

2021-02-15 09:23 UTC, gaeldestrem commented on src/js/app/pages/charte_engagement/charte_engagement.pug
>      </div>
Je suis également d'accord, je pense que ça vaut le coup de prendre un peu de temps pour repasser sur ce fichier afin de l'homogénéiser avec la nouvelle "convention tech" sur les nouveaux composants

Idéalement, faudrait également pouvoir enlever la classe css v1 à la racine du fichier pour etre sure qu'on s'appuie pas sur ces anciens styles

2021-02-15 09:23 UTC, gaeldestrem commented on src/js/app/pages/charte_engagement/charte_engagement.scss
> +}
Yes, je suis en phase 👍

2021-02-15 09:47 UTC, ch-benard commented on src/js/helpers/api/user.js
> +        data: false,
Héritée de la version n-1. data correspond à la seule case à cocher qui existait pour valider la charte:

```html
<input type="checkbox" id="charte" value="1" v-model="data" :disabled="form.status === 'pending'" class="input input--checkbox" />
```
Je corrige avec un nom de variable plus évocateur.

2021-02-15 15:01 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.pug
>      </div>
Fait. Tout est regroupé dans un seul fichier `CharteEngagement/CharteEngagement.vue`

2021-02-18 12:26 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.scss
> +}
C'est corrigé.

2021-02-18 12:27 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.scss
> +}
Corrigé. Utilisation de la classe _bg-yellow-200_.

2021-02-18 12:28 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.pug
> +                    <div>En validant mon accès, <strong>je m’engage à contribuer et à utiliser la plateforme dans une optique de résorption des bidonvilles selon l'approche humaine et pragmatique déc
C'est fait.

2021-02-18 12:28 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.pug
> +                                <img v-else src="/img/spinner_light.svg" width="20" />
Remplacé par un bouton avec chargement.

2021-02-18 12:28 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.pug
> +                    <div>Je m'engage également à <strong>exploiter les informations présentes sur la plateforme exclusivement pour les besoins propres de mon organisation ; à ne pas communiquer</stro
C'est corrigé.

2021-02-19 11:05 UTC, ch-benard commented on src/js/app/pages/charte_engagement/charte_engagement.js
> +            acceptCharte(
Effectivement, on gagne en lisibilité. C'est corrigé.

2021-02-19 11:16 UTC, ch-benard commented on src/js/helpers/api/user.js
> +export function acceptCharte(userId, charteVersion, confidentiality_agreement) {
C'est corrigé.

2021-03-03 11:25 UTC, anis requested changes
Un dernier changement, probablement une question de secondes à corriger 😄

2021-03-03 11:25 UTC, anis commented on src/js/app/pages/CharteEngagement/CharteEngagement.vue
> +        <div class="v1 print:hidden">
il faut retirer le `v1` : l'idée à long terme c'est de ne plus utiliser les anciens styles, donc on refait chaque nouvelle page sans ces derniers pour remplacer petit à petit :)

2021-03-08 11:15 UTC, merged