(691) J'interviens ici
MTES-MCT/action-bidonvilles pull request #62
Opened 2021-02-19 16:49 UTC by anis

2021-02-25 09:51 UTC, gaeldestrem requested changes
Première passe, je suis allé vite sur la fin, il faudra que je rejette un coup d'oeil

2021-02-25 09:51 UTC, gaeldestrem commented on src/js/app/components/ui/Button.vue
> +        :to="isLink ? (disabled ? null : href) : null"
Je me demande si ça va pas introduire une regression par rapport aux bannières sur la homepage qui renvoit sur des liens externes via un boutton

On a actuellement le computed suivant
```
isLink() {
    return this.href !== undefined;
}
```

on pourrait rajouter une prop isRouterLink et gérer ces 2 cas
```
isRouterLink() {
    return this.to !== undefined;
}
```

2021-02-25 09:51 UTC, gaeldestrem commented on src/js/app/pages/TownDetails/TownDetailsActorThemes.vue
> +                        <ValidationProvider vid="user_id"></ValidationProvider>
Je suis pas un expert de VeeValidate meme si je l'ai mis en place '^^ Pourquoi on a besoin de ça?

2021-02-25 09:51 UTC, gaeldestrem commented on src/js/app/pages/TownDetails/TownDetailsActorThemes.vue
> +        let value = [];
Je trouve les ternaires plus lisibles pour ce genre de trucs
```
const value = actor !== undefined ? actor.themes : []
```

2021-02-25 09:51 UTC, gaeldestrem commented on src/js/app/pages/TownDetails/TownDetailsActorThemes.vue
> +    height: 500px;
Hmm je me suis fait avoir sur les modals en pensant etre safe avec un container de 500px, faut peut etre remplacer le container scrollable par des vh

https://trello.com/c/VTJQfo0D/816-bouton-valider-non-accessible-sur-la-pop-up-fermer-un-site-sur-firefox
https://github.com/MTES-MCT/action-bidonvilles/pull/63/files

2021-02-25 09:51 UTC, gaeldestrem commented on src/js/app/pages/TownDetails/TownDetails.vue
> +        <TownDetailsActorThemes
Je rajouterais le suffix Modal à ce composant `TownDetailsActorThemesModal` ?

2021-03-04 11:39 UTC, anis commented on src/js/app/pages/TownDetails/TownDetailsActorThemes.vue
> +                        <ValidationProvider vid="user_id"></ValidationProvider>
En fait la propriété "user_id" ne correspond à aucun champ dans le formulaire, du coup si l'api retourne une erreur pour cette propriété elle n'apparaît nulle part parce que vee validate ne voit aucun champ correspondant.
Pour contourner, j'ai rajouté ce provider. C'est artificiel mais au moins l'erreur apparaît si besoin.

2021-03-04 11:48 UTC, anis commented on src/js/app/components/ui/Button.vue
> +        :to="isLink ? (disabled ? null : href) : null"
Bah écoute je viens de tester et les bannières semblent toujours intactes :)

2021-03-05 09:10 UTC, gaeldestrem approved these changes

2021-03-08 09:52 UTC, merged