Ajout de Sentry pour le tracking d'erreurs
MTES-MCT/action-bidonvilles pull request #87
Opened 2021-03-17 18:34 UTC by gaeldestrem

2021-03-25 11:15 UTC, anis requested changes
Deux petits trucs à changer

2021-03-25 11:15 UTC, anis commented on src/js/index.js
> +if (process.env.VUE_APP_SENTRY_RELEASE) {
Cette variable est toujours set, pourquoi cette condition ? 🤔

2021-03-25 11:15 UTC, anis commented on vue.config.js
> +                    "13dc3d0b5cd94173b25d34ba54e7975365bbc073218a4b1aa17fe5a35fa26bb2",
C'est pas une info sensible ?

2021-03-29 12:57 UTC, gaeldestrem commented on src/js/index.js
> +if (process.env.VUE_APP_SENTRY_RELEASE) {
C'est une typo, je voulais check `VUE_APP_SENTRY` et non `VUE_APP_SENTRY_RELEASE`

2021-03-29 12:59 UTC, gaeldestrem commented on vue.config.js
> +                    "13dc3d0b5cd94173b25d34ba54e7975365bbc073218a4b1aa17fe5a35fa26bb2",
my bad, j'ai regéneré la clé et passé ça sous variable d'env `VUE_APP_SENTRY_SOURCEMAP_AUTHKEY`

La clé est accessible ici : https://sentry.io/settings/account/api/auth-tokens/

2021-03-29 14:27 UTC, merged